FORMAT: 1A
HOST: https://rtp.persoo.ai


# Persoo RTP API

Real-time processing unit (RTP) is the worker of the 
Persoo cloud that processes requests reported from 
browsers or web servers and provides data for personalizations in the response.


## Uses

This API is used for reporting events or for requesting products/items from recommendation or search algorithms.


## Terminology

* **Visitor** - real website visitor. He uses several 
browsers or devices identified by VID (Visitor ID, i.e. cookie), 
email hash, user ID, etc.
* **Client** - owner of the website.
* **User** - someone configuring Persoo for a client.

## JSON/JSONP
All methods supports JSON and JSONP. Format is selected by suffix (file type)
in request's pathname:
* **.js** for JSONP (response is javascript)
* **.json** for JSON

Javascript in JSONP response calls the `function persoo.response.push()` with the JSON response as the argument. 
The caller is responsible for implementing this function.

When working in javascript, use [javascript client](https://confluence.persoo.cz/display/DOC/Javascript+Data+Collection) for sending and receiving request instead of raw API.

Why do we support JSONP? It's necessary for the javascript client in web browsers,
since they enforce CORS restrictions (disallow cross domain requests).

## Request products/items for current visitor [/{account_id}/{environment_id}/workflow.json?_t={timestamp}&_vid={browser_id}&_a={agent}&_e={event}&_url={requesting_page}&_ref={referring_page}&_debug={debug}&idsOnly={ids_only}&sortByField={sortby_field}&sortOrder={sort_order}&pageType={page_type}&itemID={item_id}&categoryID={category_id}&hiearchy={hierarchy}&algorithmID={algorithm_id}&offerID={offer_id}&locationID={location_id}&index={index}&itemsPerPage={items_per_page}&page={page}&basketItems={basket_items}&query={query}&idType={id_type}&idValue={id_value}&boolQuery={bool_query}&{customfields}]
Usually, javascript client keeps visitor identification in a cookie and uses JSONP version
to report visitor interactions and to receive personalizations as HTML fragments.

+ Parameters
    + timestamp (optional, number, `1678369882717`) ... Timestamp when the request was sent
    + account_id (required, string, `f952tmgo0k7vpil7kcef10o4`) ... ID of an account.
    + environment_id (required, string, `p`) ... ID of an environment. 
          Accepts 'p' for production and 'test' for staing environment.
    + browser_id (required, string, `AAABQAg1a7sMJnpF6WlwIFuC`) ... Visitor ID, 
          which identifies browser or device. 
          Created by JS Persoo snippet and stored in the `persooVid` cookie. 
          Alternatively can be generated server-side.
    + agent (required, string, `my-server-3`) ... ID of webserver, who calls this API.
    + referring_page (required, string, `https://mywebsite.com`) ... URL of the requesting page.
    + debug (optional, boolean, `false`) ... Whether to include debug information in the response. Default is false.   
    + event (required, string, `getRecommendation`) ... Event name. Usually 'pageview', 'statistics', 'addToBasket' and other.
    + requesting_page (required, string, `https://mywebsite.com`) ... URL or ID of the requesting page.
    + sortby_field (optional, string, `price`) ... Any numeric attribute of the returned item. This sorting overrides default ordering calculated by the algorithm.
    + sort_order (optional, string, `asc`) ... Specifies ascending or descending sort order. Accepts 'asc' and 'desc'.
    + ids_only (optional, boolean, `true`) ... Whether itemIDs only or all allowed product metadata. Default is false.
    + query (optional, string, `men shoes`) ... Context: search query, when requesting search algorithm.
    + page_type (required, string, `homepage`) ... Context: pageType of the requesting page, usually 'homepage', 'category', 'detail', 'basket' etc.
    + item_id (optional, string, `PROD001`) ... Context: itemID of the product the event is relating to.
    + category_id (optional, string, `Smart phones`) ... Context: categoryID of the category the event is relating to.
    + hierarchy (optional, string, `Electonics:Phones:Smart phones`) ... Context: category hierarchy as given in page breadcrumb.
    + customfields (optional, string, `customField=customValue`) ... Other potential custom fields.
    + algorithm_id (required, string `persooProductsFulltextSearch`) ... ID of the requested algorithm. 
        Algorithm represents product selection logic for the given offer. 
        Provided by Persoo.
    + offer_id (optional, string, `f5b8911747b04e8dadb97be5ac8af431`) ... ID of the requested offer. 
        Offer represents one recommendation or search component. 
        Various components can be placed within one location depending on the conditions. 
        Needed for proper analytics function. Provided by Persoo.
    + location_id (optional, string, `f5b8911747b04e8dadb97be5ac8af431`) ... ID of the requested location. 
        Location represent one specific location in the website layout. 
        Needed for proper analytics function. Provided by Persoo.
    + index (optional, string, `products`) ... ID of the requested index. Needed for proper analytics function. Provided by Persoo.
    + items_per_page (optional, number, `12` ) ... Number of items returned when using pagination. Default: 30
    + page (optional, number, `3`) ... Pagination number of page requested. Starts at zero. Default: 0
    + id_type (optional, string, `storeID`) ... Visitor ID for custom identification tagging. Paired with idValue.
    + id_value (optional, string, `C2223`) ... Value of the Visitor ID specified in idType. Paired with idType.
    + basket_items (optional, string, `{"214-10698":{"quantity":"2","price":1129.57},"214-21162":{"quantity":"1","price":38.26}}`) ... Context: encoded object with products in basket in the moment of event sending.
    + bool_query (optional, string, `%7B%22must%22%3A%5B%7B%22type%22%3A%22customRule%22%2C%22fields%22%3A%5B%22brand%22%2C%22%24in%22%2C%22value%22%2C%22%5C%22Adidas%5C%22%22%5D%7D%5D%7D`) ... Filters for the request. Accepts URI-valid encoded object such as: {"must":[{"type":"customRule","fields":["brand","$in","value","\"Styx\""]}]}
        For numeric values use $gte and $lte for "greater than" and "lower than":
        {"must":[{"type":"customRule","fields":["price","$gte","value","9"]},{"type":"customRule","fields":["price","$lte","value","15"]}]}


### workflow.json [GET]

+ Request

    + Headers

            Cookie: persooVID={visitor_id};
            Referer: http://my.website.com

+ Response 200 (application/json)
    + Body
    
            {
            "data": {
                    "aggregations": {
                        "brand": {
                            "terms": [
                                {
                                    "count": 42,
                                    "value": "Converse"
                                }
                            ]
                        },
                        "category_level0": {
                            "terms": [
                                {
                                    "count": 35,
                                    "value": "Shoes"
                                },
                                {
                                    "count": 5,
                                    "value": "Clothing"
                                },
                                {
                                    "count": 2,
                                    "value": "Accessories"
                                }
                            ]
                        },
                        "category_level1": {
                            "terms": [
                                {
                                    "count": 17,
                                    "value": "Shoes > High Tops"
                                },
                                {
                                    "count": 15,
                                    "value": "Shoes > Low"
                                },
                                {
                                    "count": 3,
                                    "value": "Clothing > Caps"
                                },
                                {
                                    "count": 3,
                                    "value": "Shoes > Ballerinas"
                                },
                                {
                                    "count": 1,
                                    "value": "Accessories > Backpacks"
                                },
                                {
                                    "count": 1,
                                    "value": "Accessories > Sacks"
                                },
                                {
                                    "count": 1,
                                    "value": "Clothing > Hats"
                                },
                                {
                                    "count": 1,
                                    "value": "Clothing > Vests and Tops"
                                }
                            ]
                        },
                        "colors": {
                            "terms": [
                                {
                                    "count": 9,
                                    "value": "black"
                                },
                                {
                                    "count": 8,
                                    "value": "blue"
                                },
                                {
                                    "count": 6,
                                    "value": "pink"
                                },
                                {
                                    "count": 5,
                                    "value": "white"
                                },
                                {
                                    "count": 3,
                                    "value": "beige"
                                },
                                {
                                    "count": 3,
                                    "value": "brown"
                                },
                                {
                                    "count": 2,
                                    "value": "gray"
                                },
                                {
                                    "count": 2,
                                    "value": "green"
                                },
                                {
                                    "count": 2,
                                    "value": "red"
                                },
                                {
                                    "count": 1,
                                    "value": "burgundy"
                                },
                                {
                                    "count": 1,
                                    "value": "purple"
                                }
                            ]
                        },
                        "gender": {
                            "terms": [
                                {
                                    "count": 42,
                                    "value": "women"
                                },
                                {
                                    "count": 30,
                                    "value": "men"
                                }
                            ]
                        },
                        "price": {
                            "numeric": {
                                "avg": 53.73428571428572,
                                "max": 86.04,
                                "min": 15.13
                            }
                        },
                        "productType": {
                            "terms": [
                                {
                                    "count": 17,
                                    "value": "Shoes > High Tops"
                                },
                                {
                                    "count": 15,
                                    "value": "Shoes > Low"
                                },
                                {
                                    "count": 3,
                                    "value": "Clothing > Caps"
                                },
                                {
                                    "count": 3,
                                    "value": "Shoes > Ballerinas"
                                },
                                {
                                    "count": 1,
                                    "value": "Accessories > Backpacks"
                                },
                                {
                                    "count": 1,
                                    "value": "Accessories > Sacks"
                                },
                                {
                                    "count": 1,
                                    "value": "Clothing > Hats"
                                },
                                {
                                    "count": 1,
                                    "value": "Clothing > Vests and Tops"
                                }
                            ]
                        }
                    },
                    "externalRequestID": null,
                    "itemFieldValues": {
                        "brand": [
                            "Converse"
                        ],
                        "categoryID": [
                            "Accessories > Sacks",
                            "Clothing > Vests and Tops",
                            "Accessories > Backpacks",
                            "Clothing > Caps",
                            "Clothing > Hats",
                            "Shoes > High Tops",
                            "Shoes > Low"
                        ],
                        "colors": [],
                        "id": [
                            "13634C-600",
                            "14680C-102",
                            "410851-452",
                            "512426",
                            "526584",
                            "527086",
                            "527703",
                            "C144826F",
                            "C149510",
                            "C149511",
                            "C149858",
                            "C150143",
                            "C150148",
                            "C150152",
                            "C151030",
                            "C151122",
                            "C151438",
                            "C153513",
                            "C153674",
                            "C153795",
                            "C153820",
                            "C544850",
                            "C547156",
                            "C551561"
                        ],
                        "itemGroupID": [
                            "13634C-600",
                            "14680C-102",
                            "410851-452",
                            "512426",
                            "526584",
                            "527086",
                            "527703",
                            "C144826F",
                            "C149510",
                            "C149511",
                            "C149858",
                            "C150143",
                            "C150148",
                            "C150152",
                            "C151030",
                            "C151122",
                            "C151438",
                            "C153513",
                            "C153674",
                            "C153795",
                            "C153820",
                            "C544850",
                            "C547156",
                            "C551561"
                        ],
                        "itemID": [
                            "888753319637_13634C-600",
                            "888753368147_14680C-102",
                            "847519030582_410851-452",
                            "040077512426_512426",
                            "040077526584_526584",
                            "040077527086_527086",
                            "040077527703_527703",
                            "886955046733_C144826F",
                            "886956228053_C149510",
                            "886956228251_C149511",
                            "886956117647_C149858",
                            "886956276559_C150143",
                            "886956277457_C150148",
                            "886956278317_C150152",
                            "888753244007_C151030",
                            "888753222258_C151122",
                            "888753138917_C151438",
                            "888753657616_C153513",
                            "888753820515_C153674",
                            "888753824919_C153795",
                            "888753827514_C153820",
                            "886955062641_C544850",
                            "886955748811_C547156",
                            "888753288919_C551561"
                        ],
                        "pageType": [],
                        "productType": [
                            "Accessories > Sacks",
                            "Clothing > Vests and Tops",
                            "Accessories > Backpacks",
                            "Clothing > Caps",
                            "Clothing > Hats",
                            "Shoes > High Tops",
                            "Shoes > Low"
                        ],
                        "section": [],
                        "subSection": []
                    },
                    "items": [],
                    "itemsCount": 42,
                    "itemsPerPage": 24,
                    "page": 0,
                    "pagesCount": 2,
                    "table": "products"
                },
                "exceptions": [],
                "functionCalls": []
            }